version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_E2E_AUTOMATIONProject
  gitServerName: MJANGIT
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
